### ISSUE TITLE
Visitor counter adds +3 upto +9 visits on 1 reload of the page.

### ISSUE THREAD

**Issue by mrlunk** [Tech1k/hellopico#1]
Visitor counter adds +3 up to +9 visits after page reload,
while I am the only one testing the page.

Greetings,
Peter Lunk

**Comment by Tech1k** [comment]
Thank you for letting me know about this! I've fixed this in the most recent commit on both branches (a538dbbb3144ef1623e221ea78cf1a65e3051dbc) and rewrote the code to handle the requests (it now works behind Cloudflare).

**Comment by mrlunk** [comment]
> Thank you for letting me know about this! I've fixed this in the most recent commit on both branches ([a538dbb](https://github.com/Tech1k/hellopico/commit/a538dbbb3144ef1623e221ea78cf1a65e3051dbc)) and rewrote the code to handle the requests (it now works behind Cloudflare).

Thanks for the quick fix and no problem :) 

PL.
